"use client";
import { useCallback, useEffect, useState } from "react";
import { getUpcomingClanEvents, setClanEventParticipation, removeClanEventParticipation, clanEventMediaUrl, type ClanEventWithParticipation, type ParticipationStatus } from "@/services/clan-events.service";

const typeLabels:Record<string,string>={COLLECTE:"Collecte",COMBAT:"Combat",CEREMONIE:"Cérémonie",REUNION:"Réunion",SORTIE:"Sortie",AUTRE:"Événement"};
const responseLabels:Record<ParticipationStatus,string>={ACCEPTED:"Je participe",MAYBE:"Peut-être",DECLINED:"Je ne participe pas"};
function formatDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?"Date inconnue":d.toLocaleString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"});}
function remaining(v?:string){if(!v)return "";const ms=new Date(v).getTime()-Date.now();if(ms<=0)return "En cours";const h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60;return h?`Dans ${h} h${m?` ${m}`:""}`:`Dans ${m} min`;}
export default function EvenementsPage(){
 const [events,setEvents]=useState<ClanEventWithParticipation[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");setEvents(await getUpcomingClanEvents());}catch(e){setError(e instanceof Error?e.message:"Impossible de charger les événements.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function respond(id:string,status:ParticipationStatus){try{setBusy(id);setError("");await setClanEventParticipation(id,status);await load();}catch(e){setError(e instanceof Error?e.message:"Impossible d'enregistrer votre réponse.");}finally{setBusy(null);}}
 async function clear(id:string){try{setBusy(id);await removeClanEventParticipation(id);await load();}catch(e){setError(e instanceof Error?e.message:"Impossible de retirer votre réponse.");}finally{setBusy(null);}}
 return <main className="min-h-screen bg-[#06120b] px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-6xl">
  <header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-amber-400">Le Pacte du Chêne</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-bold">Événements</h1><p className="mt-2 text-green-300">Les rendez-vous du Pacte, leurs objectifs et vos réponses.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-lg border border-amber-700 bg-amber-600 px-5 py-3 font-semibold hover:bg-amber-500 disabled:opacity-50">{loading?"Chargement…":"Actualiser"}</button></div></header>
  {error&&<div className="mb-6 rounded-xl border border-red-800 bg-red-950/60 p-4 text-red-200">{error}</div>}
  {!loading&&!events.length&&<section className="rounded-2xl border border-green-800 bg-[#0b2818]/95 p-14 text-center shadow-2xl"><div className="text-5xl">🌳</div><h2 className="mt-4 text-2xl font-bold">Aucun événement à venir</h2><p className="mt-2 text-green-300">Le calendrier du Pacte est actuellement calme.</p></section>}
  <div className="space-y-7">{events.map(({event,participation,counts})=><article id={`event-${event.eventId}`} key={event.eventId} className="overflow-hidden rounded-2xl border border-green-800 bg-[#092317]/95 shadow-2xl">
   {event.imageUrl&&<div className="relative flex min-h-[240px] w-full items-center justify-center overflow-hidden border-b border-green-900 bg-[#020806] sm:min-h-[300px] lg:min-h-[340px]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(21,65,42,.35),rgba(2,8,6,.98)_72%)]"/>
    <img src={clanEventMediaUrl(event.imageUrl)} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-10 blur-3xl"/>
    <img src={clanEventMediaUrl(event.imageUrl)} alt="" className="relative z-10 max-h-[240px] max-w-[92%] object-contain drop-shadow-[0_18px_35px_rgba(0,0,0,.65)] sm:max-h-[300px] lg:max-h-[340px]"/>
   </div>}
   <div className="border-b border-green-800 bg-[#0d2c1b] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-amber-600/20 px-3 py-1 text-xs font-bold uppercase text-amber-300">{typeLabels[event.type]??"Événement"}</span><span className="rounded-full border border-green-700 px-3 py-1 text-xs uppercase text-green-300">{event.mode==="LONG"?"Mission longue":"Action"}</span>{event.recurrence?.enabled&&<span className="rounded-full border border-amber-700/60 px-3 py-1 text-xs text-amber-300">Récurrent</span>}</div><h2 className="mt-3 text-2xl font-bold">{event.title}</h2></div>{participation&&<span className="rounded-full border border-green-600 bg-green-950 px-4 py-2 text-sm text-green-200">{responseLabels[participation]}</span>}</div></div>
   <div className="p-6"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-green-800 bg-[#061a10] p-4"><p className="text-xs font-bold uppercase text-amber-400">Début</p><p className="mt-2 font-semibold text-green-100">{formatDate(event.startsAt)}</p><p className="mt-1 text-sm text-amber-300">{remaining(event.startsAt)}</p></div><div className="rounded-xl border border-green-800 bg-[#061a10] p-4"><p className="text-xs font-bold uppercase text-amber-400">Durée</p><p className="mt-2 font-semibold text-green-100">{event.durationMinutes?`${event.durationMinutes>=60?`${Math.floor(event.durationMinutes/60)} h`:``}${event.durationMinutes%60?` ${event.durationMinutes%60} min`:``}`:"—"}</p></div>{event.location&&<div className="rounded-xl border border-green-800 bg-[#061a10] p-4"><p className="text-xs font-bold uppercase text-amber-400">Lieu</p><p className="mt-2 font-semibold text-green-100">{event.location}</p></div>}</div>
   {event.description&&<p className="mt-6 whitespace-pre-line leading-7 text-green-100">{event.description}</p>}
   {!!event.objectives?.length&&<section className="mt-7"><h3 className="text-lg font-bold text-amber-300">Objectifs</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{event.objectives.map(o=><div key={o.objectiveId} className="rounded-xl border border-green-800 bg-[#061a10] p-4"><p className="font-semibold">{o.required?"◆":"◇"} {o.title}</p>{o.description&&<p className="mt-1 text-sm text-green-300">{o.description}</p>}</div>)}</div></section>}
   {!!event.rewards?.length&&<section className="mt-7"><h3 className="text-lg font-bold text-amber-300">Récompenses</h3><div className="mt-3 flex flex-wrap gap-3">{event.rewards.map(r=><span key={r.rewardId} className="rounded-lg border border-amber-800/70 bg-amber-950/30 px-4 py-2 text-sm text-amber-200">{r.amount} {r.currencyId}{r.label?` · ${r.label}`:""}</span>)}</div></section>}
   <div className="mt-7 border-t border-green-800 pt-5"><div className="flex flex-wrap gap-3">{(["ACCEPTED","MAYBE","DECLINED"] as ParticipationStatus[]).map(s=><button key={s} disabled={busy===event.eventId||event.participationOptions?.[s==="ACCEPTED"?"accepted":s==="MAYBE"?"maybe":"declined"]===false} onClick={()=>void respond(event.eventId,s)} className={`rounded-lg border px-4 py-2.5 text-sm font-semibold ${participation===s?"border-amber-400 bg-amber-600 text-white":"border-green-700 bg-green-950 text-green-200 hover:border-amber-500"} disabled:opacity-40`}>{responseLabels[s]}</button>)}{participation&&<button onClick={()=>void clear(event.eventId)} disabled={busy===event.eventId} className="px-3 py-2 text-sm text-green-400 hover:text-white">Effacer ma réponse</button>}</div><div className="mt-5 flex flex-wrap gap-5 text-sm text-green-300"><span><strong className="text-green-100">{counts.ACCEPTED}</strong> participants</span><span><strong className="text-amber-100">{counts.MAYBE}</strong> peut-être</span><span><strong className="text-red-100">{counts.DECLINED}</strong> absents</span></div></div>
   </div></article>)}</div>
 </div></main>;
}
